#!/usr/bin/env node
// const promiseFs = require('fs').promises;
const Path = require('path');

const fastGlob = require('fast-glob');

const initServerEnv = require('../server/utils/environment');
const { buildStaticPage } = require('../server/utils/static_pages');

initServerEnv();

const SOURCE_TEMPLATES_GLOB = Path.join(__dirname, '../src/views/static/*.pug');

async function run() {
  (await fastGlob(SOURCE_TEMPLATES_GLOB, { onlyFiles: true })).forEach(
    async (filename) => {
      try {
        await buildStaticPage(filename);
      } catch (error) {
        process.stderr.write(`Error on processing template:\n${error}`);
      }
    }
  );
}

run();
